// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubefs/blobstore/api/tinker (interfaces: VolInfoUpdater)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/cubefs/blobstore/common/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockVolInfoUpdater is a mock of VolInfoUpdater interface.
type MockVolInfoUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockVolInfoUpdaterMockRecorder
}

// MockVolInfoUpdaterMockRecorder is the mock recorder for MockVolInfoUpdater.
type MockVolInfoUpdaterMockRecorder struct {
	mock *MockVolInfoUpdater
}

// NewMockVolInfoUpdater creates a new mock instance.
func NewMockVolInfoUpdater(ctrl *gomock.Controller) *MockVolInfoUpdater {
	mock := &MockVolInfoUpdater{ctrl: ctrl}
	mock.recorder = &MockVolInfoUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolInfoUpdater) EXPECT() *MockVolInfoUpdaterMockRecorder {
	return m.recorder
}

// UpdateVolInfo mocks base method.
func (m *MockVolInfoUpdater) UpdateVolInfo(arg0 context.Context, arg1 string, arg2 proto.Vid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVolInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVolInfo indicates an expected call of UpdateVolInfo.
func (mr *MockVolInfoUpdaterMockRecorder) UpdateVolInfo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVolInfo", reflect.TypeOf((*MockVolInfoUpdater)(nil).UpdateVolInfo), arg0, arg1, arg2)
}
